add all steps of the fourth homework
PetroBabiuk/nodejs-homework-rest-api pull request #3
Opened 2021-11-23 13:12 UTC by PetroBabiuk

2021-11-23 18:43 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const { page, limit } = req.query;
сделай проверку на эти два параметра - чтобы они были числами
если не число вернуть ошибку bad request

2021-11-23 18:44 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
если сделать запрос на список контактов без авторизации - приложение сломается

2021-11-23 18:45 UTC, KirillKulakow commented on routes/api/auth.js
> +router.post(
пропущен шаг 5

2021-11-23 18:46 UTC, KirillKulakow requested changes
Need fix

2021-11-23 18:47 UTC, KirillKulakow commented
И было бы хорошо сделать запросы по контактам с привязкой не только к ид контакта но и к ид собственника
чтобы контакт определенного юзера мог удалить только его собственник(это касается не только удаления)

2021-11-24 13:43 UTC, PetroBabiuk commented on routes/api/auth.js
> +router.post(
done

2021-11-24 13:43 UTC, PetroBabiuk commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
done

2021-11-24 13:43 UTC, PetroBabiuk commented on controllers/contacts/getAll.js
> +  const { page, limit } = req.query;
done

2021-11-24 19:49 UTC, KirillKulakow approved these changes

2021-11-24 19:56 UTC, merged