Hw05 avatars
PetroBabiuk/nodejs-homework-rest-api pull request #4
Opened 2021-11-25 00:00 UTC by PetroBabiuk

# Домашнее задание 5

## Шаг 1

 - [x] Создай папку `public` для раздачи статики. В этой папке сделай папку `avatars`. Настрой Express на раздачу статических файлов из папки `public`.

## Шаг 2

- [x] В схему пользователя добавь новое свойство `avatarURL` для хранения изображения.

- [x] Используй пакет [gravatar](https://www.npmjs.com/package/gravatar) для того чтобы при регистрации нового пользователя сразу сгенерить ему аватар по его `email`.

## Шаг 3

При регистрации пользователя:

- [x]  - Создавай ссылку на аватарку пользователя с помощью [gravatar](https://www.npmjs.com/package/gravatar)
- [x]  - Полученный URL сохрани в поле `avatarURL` во время создания пользователя

## Шаг 4

- [x] Добавь возможность обновления аватарки, создав эндпоинт `/users/avatars` и используя метод `PATCH`.

- [x] - Создай папку tmp в корне проекта и сохраняй в неё загруженную аватарку.
- [x] - Обработай аватарку пакетом [jimp](https://www.npmjs.com/package/jimp) и задай для нее размеры 250 на 250
- [x] - Перенеси аватарку пользователя из папки tmp в папку `public/avatars` и дай ей уникальное имя для конкретного пользователя.
- [x] - Полученный `URL` `/avatars/<имя файла с расширением>` сохрани в поле `avatarURL` пользователя

2021-11-25 20:05 UTC, KirillKulakow commented on controllers/auth/signup.js
> +  const avatarURL = gravatar.url(email)
добавь опцию протокола для корректной ссылки на аватар

2021-11-25 20:06 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
можешь добавить проверку на MIME тип файла чтобы можно было записать только картинки

2021-11-25 20:07 UTC, KirillKulakow requested changes
Need some fix

2021-11-26 22:50 UTC, PetroBabiuk commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
done

2021-11-26 22:50 UTC, PetroBabiuk commented on controllers/auth/signup.js
> +  const avatarURL = gravatar.url(email)
done

2021-11-27 17:30 UTC, KirillKulakow commented on controllers/auth/signup.js
> +  const avatarURL = `http:${avatarURLWithoutHTTP}`
плохое решение
https://github.com/emerleite/node-gravatar

2021-11-27 17:30 UTC, KirillKulakow approved these changes

2021-11-28 00:56 UTC, PetroBabiuk commented on controllers/auth/signup.js
> +  const avatarURL = `http:${avatarURLWithoutHTTP}`
fixed

2021-11-28 21:51 UTC, KirillKulakow approved these changes

2021-11-29 06:54 UTC, merged