Hw06 email
PetroBabiuk/nodejs-homework-rest-api pull request #5
Opened 2021-12-02 18:30 UTC by PetroBabiuk

# Домашнее задание 6

## Шаг 1

 - [ ] Подготовка интеграции с SendGrid API
 - [x] регистрация на мета.юа

## Шаг 2

### Создание ендпоинта для верификации email'а

 - [x] - добавить в модель `User` два поля `verificationToken` и `verify`. Значение поля `verify` равное `false` будет означать, что его email еще не прошел верификацию

 - [x] - создать эндпоинт GET [`/users/verify/:verificationToken`](#verification-request), где по параметру `verificationToken` мы будем искать пользователя в модели `User`
 - [x] - если пользователь с таким токеном не найден, необходимо вернуть [Ошибку 'Not Found'](#verification-user-not-found)
 - [x] - если пользователь найден - устанавливаем `verificationToken` в `null`, а поле `verify` ставим равным `true` в документе пользователя и возвращаем [Успешный ответ](#verification-success-response)

## Шаг 3

### Добавление отправки email пользователю с ссылкой для верификации

При создания пользователя при регистрации:

 - [x] - создать `verificationToken` для пользователя и записать его в БД (для генерации токена используйте пакет [uuid](https://www.npmjs.com/package/uuid) или [nanoid](https://www.npmjs.com/package/nanoid))
 - [x] - отправить email на почту пользователя и указать ссылку для верификации email'а (`/users/verify/:verificationToken`) в сообщении
 - [x] - Так же необходимо учитывать, что теперь логин пользователя не разрешен при не верифицированном email

## Шаг 4

### Добавление повторной отправки email пользователю с ссылкой для верификации

Необходимо предусмотреть, вариант, что пользователь может случайно удалить письмо. Оно может не дойти по какой-то причине к адресату. Наш сервис отправки писем во время регистрации выдал ошибку и т.д.

#### @ POST /users/verify/

 - [x] - Получает `body` в формате `{ email }`
 - [x] - Если в `body` нет обязательного поля `email`, возвращает json с ключом `{"message": "missing required field email"}` и статусом `400`
 - [x] - Если с `body` все хорошо, выполняем повторную отправку письма с `verificationToken` на указанный email, но только если пользователь не верифицирован
 - [x] - Если пользователь уже прошел верификацию отправить json с ключом `{ message: "Verification has already been passed"}` со статусом `400 Bad Request`

 - [x] > Примечание: Как альтернативу SendGrid можно использовать пакет [nodemailer](https://www.npmjs.com/package/nodemailer)

2021-12-02 20:31 UTC, KirillKulakow commented on controllers/auth/login.js
> +  if (!user || !user.verify) {
поесть если юзер не верифицировал имейл - у него неверный пароль?

2021-12-02 20:32 UTC, KirillKulakow commented on controllers/auth/repeatVerify.js
> +  if (!user.verify) {
то есть если у тебя user.verify false - вернуть ошибку, верно?

2021-12-02 20:35 UTC, KirillKulakow requested changes
Need fix

2021-12-03 05:51 UTC, PetroBabiuk commented on controllers/auth/login.js
> +  if (!user || !user.verify) {
fixed

2021-12-03 05:51 UTC, PetroBabiuk commented on controllers/auth/repeatVerify.js
> +  if (!user.verify) {
fixed

2021-12-04 11:04 UTC, KirillKulakow approved these changes

2021-12-04 12:20 UTC, merged